/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject_mari_kanepaul;

import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Kane
 */
public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
    initComponents();
    loadShelfFilter();
    loadBookCards();
    JLayeredPane layeredPane = getLayeredPane();
    layeredPane.add(floatingButton, JLayeredPane.PALETTE_LAYER);
    positionFloatingButton();
}
    
    private void positionFloatingButton() {
    if (floatingButton == null) return;
    
    JLayeredPane layeredPane = getLayeredPane();
    int padding = 28; 
    
    int x = layeredPane.getWidth() - floatingButton.getWidth() - padding;
    int y = layeredPane.getHeight() - floatingButton.getHeight() - padding;
    
    floatingButton.setLocation(x, y);
}
    private void loadShelfFilter() {
    Object selected = shelfFilterComboBox.getSelectedItem();

    shelfFilterComboBox.removeAllItems();
    shelfFilterComboBox.addItem("All Shelves");

    ShelvesDAO shelvesDAO = new ShelvesDAO();
    for (String shelfCode : shelvesDAO.getShelfCodes()) {
        shelfFilterComboBox.addItem(shelfCode);
    }

    if (selected != null) {
        shelfFilterComboBox.setSelectedItem(selected);
    }
}
 
 private void handleBookAction(int copyId, boolean checkedOut) {
    LoansDAO loansDAO = new LoansDAO();
    boolean success;

    if (checkedOut) {
        success = loansDAO.checkInBook(copyId);
    } else {
        String borrowerName = JOptionPane.showInputDialog( this, "Borrower name:", "Check Out Book", JOptionPane.PLAIN_MESSAGE );
        if ( borrowerName == null || borrowerName.trim().isEmpty() ) {
            return;
        }
        int userId = new UsersDAO().getOrCreateUser( borrowerName.trim() );
        if ( userId == -1 ) {
            JOptionPane.showMessageDialog( this, "Could not create borrower." );
            return;
        }
        success = loansDAO.checkOutBook( copyId, userId );
    }
    if (!success) {
        JOptionPane.showMessageDialog(this, "Database update failed.");
    }
    loadShelfFilter();
    loadBookCards();
}
 
    private void loadBookCards() {
    booksGridPanel.removeAll();

    BooksDAO booksDAO = new BooksDAO();
    jLabel3.setText(String.valueOf(booksDAO.countAllCopies()));
    jLabel5.setText(String.valueOf(booksDAO.countAvailableCopies()));
    jLabel7.setText(String.valueOf(booksDAO.countCheckedOutCopies()));

    String searchText = searchBar.getText().trim();
    String statusFilter = String.valueOf(jComboBox1.getSelectedItem());
    String shelfFilter = String.valueOf(shelfFilterComboBox.getSelectedItem());

    for (Object[] row : booksDAO.getBookCards(searchText, statusFilter, shelfFilter)) {
        
        int copyId = ((Number) row[0]).intValue();
        String title = (String) row[1];
        String author = (String) row[2];
        String isbn = (String) row[3];
        String shelf = row[4] == null ? "No Shelf" : (String) row[4];
        String status = (String) row[5];
        String borrower = row[6] == null ? "" : (String) row[6];
        String dueDate = row[7] == null ? "" : row[7].toString();

        boolean checkedOut = "Checked Out".equalsIgnoreCase(status);

        BookCardComponent card = new BookCardComponent();
        
        card.setBookData(copyId, title, author, isbn, shelf, checkedOut, borrower, dueDate);
        
        card.setActionListener(e -> handleBookAction(copyId, checkedOut));
        
        card.setRefreshAction(() -> {
        loadShelfFilter();
        loadBookCards();
        });
        booksGridPanel.add(card);
    }
    booksGridPanel.revalidate();
    booksGridPanel.repaint();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        floatingButton = new javax.swing.JButton();
        floatingButton.setSize(56,56);
        floatingButton.putClientProperty("JButton.arc", 999);
        headerWrapperPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        subLabel = new javax.swing.JLabel();
        statsPanel = new javax.swing.JPanel();
        totalBooksCard = new javax.swing.JPanel();
        totalBooksCard.putClientProperty("FlatLaf.style", "arc: 12");
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        availableCard = new javax.swing.JPanel();
        availableCard.putClientProperty("FlatLaf.style", "arc: 12");
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkedOutCard = new javax.swing.JPanel();
        checkedOutCard.putClientProperty("FlatLaf.style", "arc: 12");
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        filterBarPanel = new javax.swing.JPanel();
        searchBar = new javax.swing.JTextField();
        searchBar.putClientProperty("JTextField.arc", 12);
        searchBar.putClientProperty("JTextField.placeholderText", "Search by title, author, ISBN...");
        searchBar.putClientProperty("JTextField.showClearButton", true);
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox1.putClientProperty("JComponent.roundRect", true);
        shelfFilterComboBox = new javax.swing.JComboBox<>();
        shelfFilterComboBox.putClientProperty("JComponent.roundRect", true);
        jScrollPane1 = new javax.swing.JScrollPane();
        booksGridPanel = new javax.swing.JPanel();

        floatingButton.setBackground(new java.awt.Color(25, 118, 210));
        floatingButton.setFont(new java.awt.Font("SansSerif", 0, 28)); // NOI18N
        floatingButton.setForeground(new java.awt.Color(255, 255, 255));
        floatingButton.setText("+");
        floatingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        floatingButton.setFocusPainted(false);
        floatingButton.addActionListener(this::floatingButtonActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        headerWrapperPanel.setBackground(new java.awt.Color(250, 250, 250));
        headerWrapperPanel.setPreferredSize(new java.awt.Dimension(1000, 320));
        headerWrapperPanel.setLayout(new java.awt.GridBagLayout());

        TitleLabel.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        TitleLabel.setText("Library Management System");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        headerWrapperPanel.add(TitleLabel, gridBagConstraints);

        subLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        subLabel.setForeground(new java.awt.Color(102, 102, 102));
        subLabel.setText("Track and manage your book collection.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 0);
        headerWrapperPanel.add(subLabel, gridBagConstraints);

        statsPanel.setOpaque(false);
        statsPanel.setPreferredSize(new java.awt.Dimension(1000, 160));
        statsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        totalBooksCard.setBackground(new java.awt.Color(25, 118, 210));
        totalBooksCard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        totalBooksCard.setMinimumSize(new java.awt.Dimension(153, 138));
        totalBooksCard.setPreferredSize(new java.awt.Dimension(123, 138));
        totalBooksCard.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        totalBooksCard.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Books");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        totalBooksCard.add(jLabel4, gridBagConstraints);

        statsPanel.add(totalBooksCard);

        availableCard.setBackground(new java.awt.Color(46, 125, 50));
        availableCard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        availableCard.setMinimumSize(new java.awt.Dimension(153, 138));
        availableCard.setPreferredSize(new java.awt.Dimension(103, 138));
        availableCard.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        availableCard.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Available");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        availableCard.add(jLabel6, gridBagConstraints);

        statsPanel.add(availableCard);

        checkedOutCard.setBackground(new java.awt.Color(239, 108, 0));
        checkedOutCard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkedOutCard.setMinimumSize(new java.awt.Dimension(153, 138));
        checkedOutCard.setPreferredSize(new java.awt.Dimension(133, 138));
        checkedOutCard.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        checkedOutCard.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Checked Out");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        checkedOutCard.add(jLabel8, gridBagConstraints);

        statsPanel.add(checkedOutCard);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        headerWrapperPanel.add(statsPanel, gridBagConstraints);

        filterBarPanel.setMinimumSize(new java.awt.Dimension(1000, 50));
        filterBarPanel.setOpaque(false);
        filterBarPanel.setPreferredSize(new java.awt.Dimension(1000, 70));
        filterBarPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        searchBar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        searchBar.setForeground(new java.awt.Color(153, 153, 153));
        searchBar.setToolTipText("");
        searchBar.setPreferredSize(new java.awt.Dimension(200, 35));
        searchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchBarFocusLost(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchBarKeyTyped(evt);
            }
        });
        filterBarPanel.add(searchBar);

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Books", "Available", "Checked Out" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(103, 25));
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 35));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        filterBarPanel.add(jComboBox1);

        shelfFilterComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        shelfFilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Shelves", "A-12", "B-05", "A-08", "C-14" }));
        shelfFilterComboBox.setMinimumSize(new java.awt.Dimension(91, 25));
        shelfFilterComboBox.setPreferredSize(new java.awt.Dimension(100, 35));
        shelfFilterComboBox.addActionListener(this::shelfFilterComboBoxActionPerformed);
        filterBarPanel.add(shelfFilterComboBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        headerWrapperPanel.add(filterBarPanel, gridBagConstraints);

        getContentPane().add(headerWrapperPanel, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1000, 480));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 480));
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        booksGridPanel.setBackground(new java.awt.Color(250, 250, 250));
        booksGridPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 30, 30));
        booksGridPanel.setLayout(new java.awt.GridLayout(0, 5, 25, 25));
        jScrollPane1.setViewportView(booksGridPanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1614, 908));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBarFocusGained

    }//GEN-LAST:event_searchBarFocusGained

    private void searchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBarFocusLost

    }//GEN-LAST:event_searchBarFocusLost

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        positionFloatingButton();
    }//GEN-LAST:event_formComponentResized

    private void floatingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floatingButtonActionPerformed
        AddBookDialog dialog = new AddBookDialog(this, true);
    dialog.setVisible(true);
    loadShelfFilter();
    loadBookCards();
    }//GEN-LAST:event_floatingButtonActionPerformed

    private void searchBarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarKeyTyped

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    loadBookCards();        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
    loadBookCards();        
    }//GEN-LAST:event_searchBarKeyReleased

    private void shelfFilterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelfFilterComboBoxActionPerformed
    if (shelfFilterComboBox.getSelectedItem() != null) {
        loadBookCards();
    }        
    }//GEN-LAST:event_shelfFilterComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel availableCard;
    private javax.swing.JPanel booksGridPanel;
    private javax.swing.JPanel checkedOutCard;
    private javax.swing.JPanel filterBarPanel;
    private javax.swing.JButton floatingButton;
    private javax.swing.JPanel headerWrapperPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchBar;
    private javax.swing.JComboBox<String> shelfFilterComboBox;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JLabel subLabel;
    private javax.swing.JPanel totalBooksCard;
    // End of variables declaration//GEN-END:variables
}
